# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.detail


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_userlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDetail',
            fields=[
                ('userlog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='repo.UserLog')),
            ],
            bases=(django.views.generic.detail.DetailView, 'repo.userlog'),
        ),
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-create_time'], 'verbose_name': '用户日志', 'verbose_name_plural': '用户日志'},
        ),
    ]
